import Head from 'next/head'
import ArticleList from '../components/ArticleList'
import styles from '../styles/Home.module.css'

export default function Home({articles}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ArticleList articles={articles}/>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=6')
  const articles = await res.json().catch(err => err.message)
  return {
    props: {
      articles
    }
  }
}